# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created.
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build, Deploy, and Upload Artifacts.

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Configure Maven settings
      run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>hello_world_war</id>
                      <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
                      <password>${{ secrets.ARTIFACTORY_API_KEY }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml   
        
    - name: Build with Maven
      run: mvn clean deploy
